/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.ActionEvent;
import javax.swing.JFileChooser;
import java.util.*;
import java.io.File;   
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author musa
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    float ttprice = 0;
    int[] cats = {0,0,0};
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sflg = new javax.swing.JButton();
        softlgtxt = new javax.swing.JLabel();
        softregtxt = new javax.swing.JLabel();
        sfreg = new javax.swing.JButton();
        softjrtxt = new javax.swing.JLabel();
        sfjr = new javax.swing.JButton();
        hotdlgtxt = new javax.swing.JLabel();
        htlg = new javax.swing.JButton();
        hotdregtxt = new javax.swing.JLabel();
        htjr = new javax.swing.JButton();
        watertxt = new javax.swing.JLabel();
        wat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        sweetbagstxt = new javax.swing.JLabel();
        sweetbagsbtn = new javax.swing.JButton();
        toffeetxt = new javax.swing.JLabel();
        tofee = new javax.swing.JButton();
        candytxt = new javax.swing.JLabel();
        candy = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        poplgtxt = new javax.swing.JLabel();
        poplg = new javax.swing.JButton();
        popregtxt = new javax.swing.JLabel();
        popreg = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        nacholgtxt = new javax.swing.JLabel();
        nachos = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        nachoregtxt = new javax.swing.JLabel();
        nachosreg = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        hotlgtxt = new javax.swing.JLabel();
        hotdoglg = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        hotregtxt = new javax.swing.JLabel();
        hotdogreg = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        combotxt = new javax.swing.JLabel();
        combo = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datatable = new javax.swing.JTable();
        jLabel49 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        savecsv = new javax.swing.JButton();
        loadcsv = new javax.swing.JButton();
        updateprices = new javax.swing.JButton();
        deleterecord = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        cleartable = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        netprice = new javax.swing.JTextPane();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        discountt = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        finalprice = new javax.swing.JTextPane();
        jLabel53 = new javax.swing.JLabel();
        clearod = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        deleteitem = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel1.setText("SOFT DRINK LARGE");

        jLabel2.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel2.setText("SOFT DRINK REGULAR");

        jLabel3.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel3.setText("SOFT DRINK JUNIOR");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/sodalg.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/sodareg.png"))); // NOI18N
        jLabel5.setAlignmentY(0.0F);
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/sodajr.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel7.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel7.setText("HOT DRINK LARGE");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/htdreg.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel9.setText("HOT DRINK REGULAR");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/hotdsm.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/water.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel14.setText("WATER 750 ML");

        sflg.setText("BUY");
        sflg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sflgMouseClicked(evt);
            }
        });

        softlgtxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        softlgtxt.setText("price");

        softregtxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        softregtxt.setText("price");

        sfreg.setText("BUY");
        sfreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sfregMouseClicked(evt);
            }
        });

        softjrtxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        softjrtxt.setText("price");

        sfjr.setText("BUY");
        sfjr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sfjrMouseClicked(evt);
            }
        });

        hotdlgtxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        hotdlgtxt.setText("price");

        htlg.setText("BUY");
        htlg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                htlgMouseClicked(evt);
            }
        });
        htlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htlgActionPerformed(evt);
            }
        });

        hotdregtxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        hotdregtxt.setText("price");

        htjr.setText("BUY");
        htjr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                htjrMouseClicked(evt);
            }
        });

        watertxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        watertxt.setText("price");

        wat.setText("BUY");
        wat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                watMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(sflg, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(softregtxt)
                                .addGap(35, 35, 35))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sfreg, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sfjr, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(softjrtxt))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(22, 22, 22)))
                        .addGap(62, 62, 62))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(hotdlgtxt))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(29, 29, 29))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(htlg, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel14)
                                                .addComponent(wat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(hotdregtxt))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(htjr, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel13))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(softlgtxt))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(watertxt)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(softlgtxt)
                            .addComponent(softregtxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sflg))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(softjrtxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sfjr))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(sfreg)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotdregtxt)
                    .addComponent(hotdlgtxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(htjr)
                    .addComponent(htlg))
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(watertxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wat)
                .addContainerGap())
        );

        jTabbedPane1.addTab("DRINKS", jPanel2);

        jLabel11.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel11.setText("SWEET BAGS");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/sweet.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel15.setText("TOFFEE POPCORN");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/toffee.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel17.setText("CANDY FLOSS");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/candy.png"))); // NOI18N

        sweetbagstxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        sweetbagstxt.setText("price");
        sweetbagstxt.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                sweetbagstxtAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        sweetbagsbtn.setText("BUY");
        sweetbagsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sweetbagsbtnMouseClicked(evt);
            }
        });

        toffeetxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        toffeetxt.setText("price");

        tofee.setText("BUY");
        tofee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tofeeMouseClicked(evt);
            }
        });

        candytxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        candytxt.setText("price");

        candy.setText("BUY");
        candy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                candyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(sweetbagsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(sweetbagstxt))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tofee, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(toffeetxt))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(candy, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(candytxt))
                                        .addComponent(jLabel17))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel16)))
                .addContainerGap(456, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sweetbagstxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sweetbagsbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toffeetxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tofee)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(candytxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(candy)
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("CONFECTIONERY", jPanel3);

        jLabel28.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel28.setText("POPCORN LARGE");

        jLabel29.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel29.setText("POPCORN REGULAR");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/popreg.png"))); // NOI18N

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/poplg.png"))); // NOI18N

        poplgtxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        poplgtxt.setText("price");

        poplg.setText("BUY");
        poplg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poplgMouseClicked(evt);
            }
        });
        poplg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poplgActionPerformed(evt);
            }
        });

        popregtxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        popregtxt.setText("price");

        popreg.setText("BUY");
        popreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popregMouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel34.setText("NACHOS LARGE");

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/nacholg.png"))); // NOI18N

        nacholgtxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        nacholgtxt.setText("price");

        nachos.setText("BUY");
        nachos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nachosMouseClicked(evt);
            }
        });
        nachos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nachosActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel37.setText("NACHOS REGULAR");

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/nachosm.png"))); // NOI18N

        nachoregtxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        nachoregtxt.setText("price");

        nachosreg.setText("BUY");
        nachosreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nachosregMouseClicked(evt);
            }
        });
        nachosreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nachosregActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel40.setText("HOTDOG LARGE");

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/htnn.png"))); // NOI18N

        hotlgtxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        hotlgtxt.setText("price");

        hotdoglg.setText("BUY");
        hotdoglg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hotdoglgMouseClicked(evt);
            }
        });
        hotdoglg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotdoglgActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel43.setText("HOTDOG REGULAR");

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/htsmm.png"))); // NOI18N

        hotregtxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        hotregtxt.setText("price");

        hotdogreg.setText("BUY");
        hotdogreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hotdogregMouseClicked(evt);
            }
        });
        hotdogreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotdogregActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel46.setText(" KIDS COMBO");

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/cake.png"))); // NOI18N

        combotxt.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        combotxt.setText("price");

        combo.setText("BUY");
        combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMouseClicked(evt);
            }
        });
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel34)
                            .addComponent(jLabel40))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(nachosreg, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel37)
                            .addComponent(jLabel29)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel44))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(hotregtxt))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(hotdogreg, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel43)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(nachoregtxt))
                                    .addComponent(jLabel38)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(poplg, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(poplgtxt))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel35))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(nacholgtxt))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(nachos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel41))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(hotlgtxt))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(hotdoglg, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(popreg, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(popregtxt))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(combotxt)
                                .addGap(28, 28, 28)))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addGap(79, 79, 79))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(popregtxt)
                            .addComponent(poplgtxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(popreg)
                            .addComponent(poplg)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(combotxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(nacholgtxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nachos)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(hotlgtxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hotdoglg))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(nachoregtxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nachosreg)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(hotregtxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hotdogreg)))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SNACKS", jPanel4);

        datatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "food", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        datatable.setShowGrid(true);
        jScrollPane1.setViewportView(datatable);

        jLabel49.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabel49.setText("CHANGE PRICES");

        jButton18.setText("REFRESH");
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton18MouseClicked(evt);
            }
        });
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        savecsv.setText("SAVE");
        savecsv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savecsvMouseClicked(evt);
            }
        });
        savecsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savecsvActionPerformed(evt);
            }
        });

        loadcsv.setText("LOAD");
        loadcsv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadcsvMouseClicked(evt);
            }
        });
        loadcsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadcsvActionPerformed(evt);
            }
        });

        updateprices.setText("UPDATE");
        updateprices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatepricesMouseClicked(evt);
            }
        });
        updateprices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepricesActionPerformed(evt);
            }
        });

        deleterecord.setText("DELETE");
        deleterecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleterecordMouseClicked(evt);
            }
        });
        deleterecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleterecordActionPerformed(evt);
            }
        });

        jLabel54.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        jLabel54.setText("PLEASE LOAD PRICES TO TABLE FROM CSV DATABASE AND UPDATE BEFORE BUYING");

        jLabel55.setFont(new java.awt.Font("Cantarell Light", 2, 15)); // NOI18N
        jLabel55.setText("REFRESH TABLE AND UPDATE ,IF ANY VALUE HAS NOT UPDATED ITS PRICE");

        cleartable.setText("CLEAR");
        cleartable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cleartableMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel49))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel55)
                                    .addComponent(jLabel54)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loadcsv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(updateprices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(savecsv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cleartable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleterecord, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel49)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel55))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(loadcsv)
                        .addGap(5, 5, 5)
                        .addComponent(savecsv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateprices)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleterecord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleartable)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MANAGEMENT", jPanel6);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel50.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("ORDER DETAILS");

        receipt.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        receipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        receipt.setShowGrid(true);
        jScrollPane3.setViewportView(receipt);
        if (receipt.getColumnModel().getColumnCount() > 0) {
            receipt.getColumnModel().getColumn(0).setResizable(false);
            receipt.getColumnModel().getColumn(1).setResizable(false);
        }

        netprice.setEditable(false);
        netprice.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        jScrollPane4.setViewportView(netprice);

        jLabel51.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        jLabel51.setText("Net price");

        jLabel52.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        jLabel52.setText("Net discount");

        discountt.setEditable(false);
        discountt.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        jScrollPane5.setViewportView(discountt);

        finalprice.setEditable(false);
        finalprice.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        jScrollPane6.setViewportView(finalprice);

        jLabel53.setFont(new java.awt.Font("Courier 10 Pitch", 0, 15)); // NOI18N
        jLabel53.setText("Total price");

        clearod.setText("CLEAR ORDER");
        clearod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearodMouseClicked(evt);
            }
        });

        jButton1.setText("CALCULATE ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel51)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel53)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(clearod)
                                        .addGap(31, 31, 31))))))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel53)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel51))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel52))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearod)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deleteitem.setText("Delete item");
        deleteitem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteitemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteitem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(deleteitem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void htlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htlgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_htlgActionPerformed

    private void poplgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poplgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poplgActionPerformed

    private void nachosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nachosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nachosActionPerformed

    private void nachosregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nachosregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nachosregActionPerformed

    private void hotdoglgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotdoglgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotdoglgActionPerformed

    private void hotdogregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotdogregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotdogregActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void savecsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savecsvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savecsvActionPerformed

    private void loadcsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadcsvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadcsvActionPerformed

    
public void tocsv(JTable table, File file){
    try{
        TableModel model = table.getModel();
        try (FileWriter csv = new FileWriter(file)) {
            for(int i = 0; i < model.getColumnCount(); i++){
                csv.write(model.getColumnName(i) + ",");
            }
            
            csv.write("\n");
            
            for(int i=0; i< model.getRowCount(); i++) {
                for(int j=0; j < model.getColumnCount(); j++) {
                    csv.write(model.getValueAt(i,j).toString()+",");
                }
                csv.write("\n");
            }
        }

    }catch(IOException e){ System.out.println(e); }
}

    private void loadcsvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadcsvMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = fileChooser.getSelectedFile();
                System.out.println("Selected file: " + selectedFile.getAbsolutePath());
                Scanner fileScanner = new Scanner(selectedFile);
                DefaultTableModel model = (DefaultTableModel) datatable.getModel();
                String fileString = fileScanner.nextLine();
           
                while(fileScanner.hasNext()==true)
                {
                    fileString = fileScanner.nextLine();
                    String[] info = fileString.split(",");
                    Object[] row = {info[0],info[1]};
                    model.addRow(row);
     
                }
                
               
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            } 
           
            
        }
    }//GEN-LAST:event_loadcsvMouseClicked

    private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked

        datatable.repaint();
    }//GEN-LAST:event_jButton18MouseClicked

    private void sweetbagstxtAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_sweetbagstxtAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_sweetbagstxtAncestorAdded

    private void savecsvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savecsvMouseClicked
        // TODO add your handling code here:
         JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {       
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());
            tocsv(datatable,selectedFile); 
        }
    }//GEN-LAST:event_savecsvMouseClicked

    private void updatepricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepricesActionPerformed
        // TODO add your handling code here:
        // String[] food = {"softdrinklg","softdrinkreg","softdrinkjr","water","hotdrinklg","hotdrinkreg","sweetbags","toffee","candy","poplg","poprg","nachoslg","nachosreg","hotdoglg","hotdogreg","combo"};
        
    }//GEN-LAST:event_updatepricesActionPerformed

    private void deleterecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleterecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleterecordActionPerformed

    private void deleterecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleterecordMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) datatable.getModel();
        datatable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        deleterecord.addActionListener((ActionEvent ae) -> {
            // check for selected row first
            if(datatable.getSelectedRow() != -1) {
                // remove selected row from the model
                model.removeRow(datatable.getSelectedRow());
                //JOptionPane.showMessageDialog(null, "Selected row deleted successfully");
            }
        });
    }//GEN-LAST:event_deleterecordMouseClicked

    private void updatepricesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatepricesMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) datatable.getModel();
        softlgtxt.setText(model.getValueAt(0, 1).toString()+" £");
        softregtxt.setText(model.getValueAt(1, 1).toString()+" £");
        softjrtxt.setText(model.getValueAt(2, 1).toString()+" £");
        hotdlgtxt.setText(model.getValueAt(3, 1).toString()+" £");
        hotdregtxt.setText(model.getValueAt(4, 1).toString()+" £");
        watertxt.setText(model.getValueAt(5, 1).toString()+" £");
        sweetbagstxt.setText(model.getValueAt(6, 1).toString()+" £");
        toffeetxt.setText(model.getValueAt(7, 1).toString()+" £");
        candytxt.setText(model.getValueAt(8, 1).toString()+" £");
        poplgtxt.setText(model.getValueAt(9, 1).toString()+" £");
        popregtxt.setText(model.getValueAt(10, 1).toString()+" £");
        nacholgtxt.setText(model.getValueAt(11, 1).toString()+" £");
        nachoregtxt.setText(model.getValueAt(12, 1).toString()+" £");
        hotlgtxt.setText(model.getValueAt(13, 1).toString()+" £");
        hotregtxt.setText(model.getValueAt(14, 1).toString()+" £");
        combotxt.setText(model.getValueAt(15, 1).toString()+" £");
    }//GEN-LAST:event_updatepricesMouseClicked

    private void sflgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sflgMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        cats[0] = 1;
        String[] prices = softlgtxt.getText().split(" ");
        float price = Float.parseFloat(prices[0]);
        
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
        String[] row = {"Soft drink Large",prices[0]+" £"};
        model.addRow(row);
        
        
    }//GEN-LAST:event_sflgMouseClicked

    private void sfregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sfregMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        String[] prices = softregtxt.getText().split(" ");
        cats[0] = 1;
        float price = Float.parseFloat(prices[0]);
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
        String[] row = {"Soft drink Regular",prices[0]+" £"};
        model.addRow(row);
    }//GEN-LAST:event_sfregMouseClicked

    private void sfjrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sfjrMouseClicked
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        String[] prices = softjrtxt.getText().split(" ");
        cats[0] = 1;
        float price = Float.parseFloat(prices[0]);
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
        String[] row = {"Soft drink Junior",prices[0]+" £"};
        model.addRow(row);
    }//GEN-LAST:event_sfjrMouseClicked

    private void htlgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_htlgMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        String[] prices = hotdlgtxt.getText().split(" ");
        cats[0] = 1;
        float price = Float.parseFloat(prices[0]);
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
        String[] row = {"Hot drink Large",prices[0]+" £"};
        model.addRow(row);
    }//GEN-LAST:event_htlgMouseClicked

    private void htjrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_htjrMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        String[] prices = hotdregtxt.getText().split(" ");
        cats[0] = 1;
        float price = Float.parseFloat(prices[0]);
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
        String[] row = {"Hot drink Regular",prices[0]+" £"};
        model.addRow(row);
    }//GEN-LAST:event_htjrMouseClicked

    private void watMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_watMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        String[] prices = watertxt.getText().split(" ");
        cats[0] = 1;
        float price = Float.parseFloat(prices[0]);
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
        String[] row = {"Water 750 ml",prices[0]+" £"};
        model.addRow(row);
    }//GEN-LAST:event_watMouseClicked

    private void clearodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearodMouseClicked
        // TODO add your handling code here:
        ttprice = 0;
        cats[0] =0;
        cats[1] =0;
        cats[2] =0;
        netprice.setText("");
        DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        int rowCount = model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        //Object[] row ={"",""};
        //model.addRow(row);
    }//GEN-LAST:event_clearodMouseClicked

    private void sweetbagsbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sweetbagsbtnMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        String[] prices = sweetbagstxt.getText().split(" ");
        cats[1] = 1;
        float price = Float.parseFloat(prices[0]);
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
       
        String[] row = {"SweetBags",prices[0]+" £"};
        model.addRow(row);
    }//GEN-LAST:event_sweetbagsbtnMouseClicked

    private void tofeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tofeeMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        String[] prices = toffeetxt.getText().split(" ");
        cats[1] = 1;
        float price = Float.parseFloat(prices[0]);
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
        String[] row = {"Toffee popcorn",prices[0]+" £"};
        model.addRow(row);
    }//GEN-LAST:event_tofeeMouseClicked

    private void candyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candyMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        String[] prices = candytxt.getText().split(" ");
        cats[1] = 1;
        float price = Float.parseFloat(prices[0]);
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
        String[] row = {"Candy floss",prices[0]+" £"};
        model.addRow(row);
    }//GEN-LAST:event_candyMouseClicked

    private void poplgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poplgMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        String[] prices = poplgtxt.getText().split(" ");
        cats[1] = 1;
        float price = Float.parseFloat(prices[0]);
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
        String[] row = {"Popcorn Large",prices[0]+" £"};
        model.addRow(row);
    }//GEN-LAST:event_poplgMouseClicked

    private void popregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popregMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        String[] prices = popregtxt.getText().split(" ");
        cats[1] = 1;
        float price = Float.parseFloat(prices[0]);
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
        String[] row = {"Popcorn Regular",prices[0]+" £"};
        model.addRow(row);
    }//GEN-LAST:event_popregMouseClicked

    private void comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        String[] prices = combotxt.getText().split(" ");
        cats[2] = 1;
        float price = Float.parseFloat(prices[0]);
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
        String[] row = {"Kids combo",prices[0]+" £"};
        model.addRow(row);
    }//GEN-LAST:event_comboMouseClicked

    private void nachosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nachosMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        String[] prices = nacholgtxt.getText().split(" ");
        cats[2] = 1;
        float price = Float.parseFloat(prices[0]);
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
        String[] row = {"Nachos large",prices[0]+" £"};
        model.addRow(row);
    }//GEN-LAST:event_nachosMouseClicked

    private void nachosregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nachosregMouseClicked
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        String[] prices = nachoregtxt.getText().split(" ");
        cats[2] = 1;
        float price = Float.parseFloat(prices[0]);
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
        String[] row = {"Nachos Regular",prices[0]+" £"};
        model.addRow(row);
    }//GEN-LAST:event_nachosregMouseClicked

    private void hotdoglgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hotdoglgMouseClicked
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        String[] prices = hotlgtxt.getText().split(" ");
        cats[2] = 1;
        float price = Float.parseFloat(prices[0]);
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
        String[] row = {"Hotdog large",prices[0]+" £"};
        model.addRow(row);
    }//GEN-LAST:event_hotdoglgMouseClicked

    private void hotdogregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hotdogregMouseClicked
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        String[] prices = hotregtxt.getText().split(" ");
        cats[2] = 1;
        float price = Float.parseFloat(prices[0]);
        ttprice =ttprice+ price;
        netprice.setText(String.valueOf(ttprice)+" £");
        String[] row = {"Hotdog Regular",prices[0]+" £"};
        model.addRow(row);
    }//GEN-LAST:event_hotdogregMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        checkdiscount();
    }//GEN-LAST:event_jButton1MouseClicked

    private void cleartableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleartableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) datatable.getModel();
        int rowCount = model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        Object[] row ={"",""};
        model.addRow(row);

    }//GEN-LAST:event_cleartableMouseClicked

    private void deleteitemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteitemMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) receipt.getModel();
        receipt.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        deleteitem.addActionListener((ActionEvent ae) -> {
            // check for selected row first
            if(receipt.getSelectedRow() != -1) {
                // remove selected row from the model
                String Value = (String) receipt.getValueAt(receipt.getSelectedRow() , receipt.getSelectedColumn());
                String[] prices = Value.split(" ");
                float price = Float.parseFloat(prices[0]);
                ttprice = ttprice - price;
                netprice.setText(String.valueOf(ttprice));
                model.removeRow(receipt.getSelectedRow());
                //JOptionPane.showMessageDialog(null, "Selected row deleted successfully");
            }
        });
       
    }//GEN-LAST:event_deleteitemMouseClicked

    private void checkdiscount()
    {
        if(cats[0] == 1 && cats [1] == 1 && cats[2] == 1)
        {
            int discount = 3;
            float finprice  = ttprice - discount;
            discountt.setText(String.valueOf(discount)+" £");
            finalprice.setText(String.valueOf(finprice)+" £");
        }else
        {
            discountt.setText(String.valueOf(0)+" £");
            finalprice.setText(String.valueOf(ttprice)+" £");
        }
    }
    /**
     * @param args the command line arguments
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(new FlatLightLaf());
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton candy;
    private javax.swing.JLabel candytxt;
    private javax.swing.JButton clearod;
    private javax.swing.JButton cleartable;
    private javax.swing.JButton combo;
    private javax.swing.JLabel combotxt;
    private javax.swing.JTable datatable;
    private javax.swing.JButton deleteitem;
    private javax.swing.JButton deleterecord;
    private javax.swing.JTextPane discountt;
    private javax.swing.JTextPane finalprice;
    private javax.swing.JLabel hotdlgtxt;
    private javax.swing.JButton hotdoglg;
    private javax.swing.JButton hotdogreg;
    private javax.swing.JLabel hotdregtxt;
    private javax.swing.JLabel hotlgtxt;
    private javax.swing.JLabel hotregtxt;
    private javax.swing.JButton htjr;
    private javax.swing.JButton htlg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton18;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton loadcsv;
    private javax.swing.JLabel nacholgtxt;
    private javax.swing.JLabel nachoregtxt;
    private javax.swing.JButton nachos;
    private javax.swing.JButton nachosreg;
    private javax.swing.JTextPane netprice;
    private javax.swing.JButton poplg;
    private javax.swing.JLabel poplgtxt;
    private javax.swing.JButton popreg;
    private javax.swing.JLabel popregtxt;
    private javax.swing.JTable receipt;
    private javax.swing.JButton savecsv;
    private javax.swing.JButton sfjr;
    private javax.swing.JButton sflg;
    private javax.swing.JButton sfreg;
    private javax.swing.JLabel softjrtxt;
    private javax.swing.JLabel softlgtxt;
    private javax.swing.JLabel softregtxt;
    private javax.swing.JButton sweetbagsbtn;
    private javax.swing.JLabel sweetbagstxt;
    private javax.swing.JButton tofee;
    private javax.swing.JLabel toffeetxt;
    private javax.swing.JButton updateprices;
    private javax.swing.JButton wat;
    private javax.swing.JLabel watertxt;
    // End of variables declaration//GEN-END:variables
}
